conda_dir:
- /sequoia/data1/rstrudel/miniconda3
code_dir:
- /sequoia/data1/rstrudel/code
job_log_dir:
- /sequoia/data1/rstrudel/exps
conda_env_name:
- robot
machine:
- inria
queues:
- zeus.q,titan.q,gaia.q,chronos.q
n_gpus:
- 1
