job_name:
- breakfast_eval
conda_env_name:
- rl0
agent:
- rl
env_name:
- UR5-EGL-BreakfastCamEnv-v0
first_epoch:
- 50
last_epoch:
- 
model_name:
- breakfast_hrlbc_nosetup/seed00
- breakfast_hrlbc_nosetup/seed01
- breakfast_hrlbc_nosetup/seed02
- breakfast_hrlbc_nosetup/seed03
- breakfast_hrlbc_nosetup/seed04
- breakfast_hrlbc_nosetup/seed05
- breakfast_hrlbc_nosetup/seed06
- breakfast_hrlbc_nosetup/seed07
log_dir:
- /sequoia/data1/rstrudel/logs
n_processes:
- 10
n_episodes:
- 50
report_folder:
- breakfast_evaluation
skill_sequence:
- 
