job_name:
- breakfast_eval
conda_env_name:
- rl1
agent:
- bc
env_name:
- UR5-EGL-BreakfastClose8CamEnv-v0
- UR5-EGL-BreakfastClose11CamEnv-v0
- UR5-EGL-BreakfastClose14CamEnv-v0
- UR5-EGL-BreakfastClose17CamEnv-v0
- UR5-EGL-BreakfastClose21CamEnv-v0
- UR5-EGL-BreakfastClose24CamEnv-v0
- UR5-EGL-BreakfastClose27CamEnv-v0
- UR5-EGL-BreakfastClose30CamEnv-v0
first_epoch:
- 92
last_epoch:
- 93
model_name:
- breakfast_film
log_dir:
- /sequoia/data1/rstrudel/logs
n_processes:
- 10
n_episodes:
- 200
report_folder:
- breakfast_close_evaluation
