conda_env_name:
- rl2
env_name:
- UR5-EGL-BreakfastCamEnv-v0
first_epoch:
- 150
hrlbc_model_name:
- breakfast_hrlbc/seed00
- breakfast_hrlbc/seed01
- breakfast_hrlbc/seed02
- breakfast_hrlbc/seed03
- breakfast_hrlbc/seed04
- breakfast_hrlbc/seed05
- breakfast_hrlbc/seed06
job_name:
- breakfast_eval
log_dir:
- /sequoia/data1/rstrudel/logs
n_processes:
- 10
n_episodes:
- 40
report_folder:
- eval
