bc_model_epoch:
- 76
bc_model_name:
- bowl_2obj_film_2b
conda_env_name:
- rl2
env_name:
- UR5-EGL-Bowl2ObjRandCamEnv-v0
hrlbc_model_name:
- bowl_2obj_hrlbc_2b_longhori
job_name:
- bowl_2obj
log_dir:
- /sequoia/data1/rstrudel/logs
max_length:
- 1000
n_processes:
- 12
seed:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
timescale:
- 60
image_augmentation:
- kinect2_learned
